version: '3.3'

services:
  postgres: 
    image: postgres:latest
    restart: always
    env_file:
     - .env
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - nft-marketplace

volumes:
  postgresql-data:

networks:
  nft-marketplace:
    external: true