version: "3.3"

services:
  marketplace:
    build:
      context: https://github.com/phhphc/nft-marketplace-back-end.git#dev
    restart: always
    command: /app/marketplace
    env_file:
      - .env
    ports:
      - 9090:9090
    networks:
      - nft-marketplace
  chain-watcher:
    build:
      context: https://github.com/phhphc/nft-marketplace-back-end.git#dev
    restart: always
    command: /app/chain-watcher
    env_file:
      - .env
    networks:
      - nft-marketplace

networks:
  nft-marketplace:
    external: true
