version: "3.3"

services:
  chain-watcher:
    build:
      context: https://github.com/phhphc/nft-marketplace-back-end.git#t/ignore-achitecture
    restart: always
    command: /app/chain-watcher
    env_file:
      - ../.env
    networks:
      - nft-marketplace

networks:
  nft-marketplace:
    external: true
