version: "3.3"

services:
  marketplace:
    build:
      context: https://github.com/phhphc/nft-marketplace-back-end.git#t/ignore-achitecture
    restart: always
    command: /app/marketplace
    env_file:
      - ../.env
    environment:
      - PORT=9090
    ports:
      - 9090:9090
    networks:
      - nft-marketplace

networks:
  nft-marketplace:
    external: true
