version: "3.3"

services:
  blockchain:
    build:
      context: .
      dockerfile: ./signer/Dockerfile
    ports:
      - 8545:8545
    volumes:
      - chain-data:/chain/signer/geth
    networks:
      - nft-marketplace
      
volumes:
  chain-data:

networks:
  nft-marketplace:
    external: true