version: "3.2"
services:
   redis-1:
      image: "redis:alpine"
      command: redis-server --requirepass 12345
      ports:
         - "6380:6379"
      environment:
         - REDIS_REPLICATION_MODE=master
      networks:
         - nft-marketplace

   redis-2:
      image: "redis:alpine"
      command: redis-server --requirepass 12345
      ports:
         - "6381:6379"
      environment:
         - REDIS_REPLICATION_MODE=master
      networks:
         - nft-marketplace

networks:
   nft-marketplace:
      external: true
